version: "3.9"
services:
  postgres:
    image: postgres:14.3
    container_name: "postgres"
    environment:
      POSTGRES_DB: "AskMe"
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: "test"
      PGDATA: "../Database/Data/pgdata"
    ports:
      - "5000:5432"
    volumes:
      - ../Database/Initialization:/docker-entrypoint-initdb.d
      - ../Database/Data/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d AskMe" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
